# Fix print template
f = open('scheduler/templates/scheduler/print_appointments.html', 'w', encoding='utf-8')
f.write('<!DOCTYPE html>\n')
f.write('<html lang="en">\n')
f.write('<head>\n')
f.write('<meta charset="UTF-8">\n')
f.write('<meta name="viewport" content="width=device-width, initial-scale=1.0">\n')
f.write('<title>Vic_nice - Appointments Report</title>\n')
f.write('<style>\n')
f.write('*{margin:0;padding:0;box-sizing:border-box;}\n')
f.write('body{font-family:"Segoe UI",sans-serif;padding:30px;color:#1a1a2e;}\n')
f.write('.header{text-align:center;margin-bottom:30px;border-bottom:3px solid #3730a3;padding-bottom:20px;}\n')
f.write('.header h1{font-size:24px;color:#3730a3;font-weight:700;}\n')
f.write('.header p{font-size:14px;color:#6b7280;margin-top:4px;}\n')
f.write('table{width:100%;border-collapse:collapse;margin-top:20px;}\n')
f.write('th{background:#3730a3;color:white;padding:10px 12px;font-size:12px;text-align:left;text-transform:uppercase;}\n')
f.write('td{padding:10px 12px;font-size:13px;border-bottom:1px solid #e5e7eb;}\n')
f.write('tr:nth-child(even) td{background:#f8f7ff;}\n')
f.write('.footer{margin-top:30px;text-align:center;font-size:12px;color:#9ca3af;}\n')
f.write('.no-print{margin-bottom:20px;}\n')
f.write('.btn{padding:10px 24px;background:#3730a3;color:white;border:none;border-radius:8px;font-size:14px;cursor:pointer;margin-right:10px;}\n')
f.write('@media print{.no-print{display:none;}body{padding:10px;}}\n')
f.write('</style>\n')
f.write('</head>\n')
f.write('<body>\n')
f.write('<div class="no-print">\n')
f.write('  <button class="btn" onclick="window.print()">Print / Save as PDF</button>\n')
f.write('  <a href="/appointments/" style="color:#3730a3;font-size:14px;">Back to Appointments</a>\n')
f.write('</div>\n')
f.write('<div class="header">\n')
f.write('  <h1>Vic_nice Home Concepts</h1>\n')
f.write('  <p>Appointments Report &mdash; Generated {{ today }}</p>\n')
f.write('</div>\n')
f.write('<table>\n')
f.write('  <thead>\n')
f.write('    <tr><th>Title</th><th>Type</th><th>Date</th><th>Time</th><th>Client / Student</th><th>Location</th><th>Status</th></tr>\n')
f.write('  </thead>\n')
f.write('  <tbody>\n')
f.write('  {% for a in appointments %}\n')
f.write('  <tr>\n')
f.write('    <td>{{ a.title }}</td>\n')
f.write('    <td>{{ a.get_type_display }}</td>\n')
f.write('    <td>{{ a.date }}</td>\n')
f.write('    <td>{{ a.start_time|default:"-" }}{% if a.end_time %} - {{ a.end_time }}{% endif %}</td>\n')
f.write('    <td>{{ a.client|default:a.student|default:"-" }}</td>\n')
f.write('    <td>{{ a.location|default:"-" }}</td>\n')
f.write('    <td>{{ a.get_status_display }}</td>\n')
f.write('  </tr>\n')
f.write('  {% endfor %}\n')
f.write('  </tbody>\n')
f.write('</table>\n')
f.write('<div class="footer">Vic_nice Home Concepts &mdash; Confidential</div>\n')
f.write('</body>\n')
f.write('</html>\n')
f.close()
print('print_appointments.html done!')

# Fix appointments template - check if appointments have data
f = open('scheduler/templates/scheduler/appointments.html', 'r', encoding='utf-8')
content = f.read()
f.close()
# Check if remind button is there
if 'remind' in content.lower():
    print('Remind button EXISTS in template')
else:
    print('Remind button MISSING from template')