f = open('scheduler/templates/scheduler/base.html', 'w', encoding='utf-8')
f.write('<!DOCTYPE html>\n')
f.write('<html lang="en">\n')
f.write('<head>\n')
f.write('<meta charset="UTF-8">\n')
f.write('<meta name="viewport" content="width=device-width, initial-scale=1.0">\n')
f.write('<title>Vic_nice Home Concepts</title>\n')
f.write('<style>\n')
f.write('*{margin:0;padding:0;box-sizing:border-box;}\n')
f.write('body{font-family:"Segoe UI",sans-serif;background:#f0f0f8;color:#1a1a2e;}\n')
f.write('.sidebar{position:fixed;top:0;left:0;width:220px;height:100vh;background:#3730a3;color:white;padding:20px 0;overflow-y:auto;z-index:1000;transition:transform 0.3s;}\n')
f.write('.sidebar .logo{padding:20px 24px 30px;font-size:18px;font-weight:700;border-bottom:1px solid #4f46e5;line-height:1.3;}\n')
f.write('.sidebar .logo span{display:block;font-size:12px;font-weight:400;opacity:0.7;margin-top:4px;}\n')
f.write('.sidebar a{display:block;padding:12px 24px;color:rgba(255,255,255,0.8);text-decoration:none;font-size:14px;transition:all 0.2s;}\n')
f.write('.sidebar a:hover{background:#4f46e5;color:white;padding-left:30px;}\n')
f.write('.main{margin-left:220px;padding:30px;}\n')
f.write('.topbar{background:white;border-radius:12px;padding:16px 24px;margin-bottom:24px;display:flex;justify-content:space-between;align-items:center;box-shadow:0 1px 4px rgba(0,0,0,0.06);}\n')
f.write('.topbar h1{font-size:20px;color:#3730a3;font-weight:700;}\n')
f.write('.topbar .date{font-size:13px;color:#6b7280;}\n')
f.write('.hamburger{display:none;background:none;border:none;cursor:pointer;padding:4px;}\n')
f.write('.hamburger span{display:block;width:24px;height:3px;background:#3730a3;margin:5px 0;border-radius:3px;transition:0.3s;}\n')
f.write('.overlay{display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.5);z-index:999;}\n')
f.write('.card{background:white;border-radius:12px;padding:24px;box-shadow:0 1px 4px rgba(0,0,0,0.06);margin-bottom:20px;}\n')
f.write('.card h2{font-size:16px;font-weight:600;color:#3730a3;margin-bottom:16px;padding-bottom:12px;border-bottom:1px solid #e5e7eb;}\n')
f.write('.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:24px;}\n')
f.write('.stat{background:white;border-radius:12px;padding:20px;box-shadow:0 1px 4px rgba(0,0,0,0.06);border-left:4px solid #3730a3;}\n')
f.write('.stat .num{font-size:32px;font-weight:700;color:#3730a3;}\n')
f.write('.stat .label{font-size:13px;color:#6b7280;margin-top:4px;}\n')
f.write('.table-wrap{overflow-x:auto;}\n')
f.write('table{width:100%;border-collapse:collapse;min-width:500px;}\n')
f.write('th{text-align:left;padding:10px 12px;font-size:12px;color:#6b7280;border-bottom:2px solid #e5e7eb;text-transform:uppercase;letter-spacing:0.05em;}\n')
f.write('td{padding:12px;font-size:14px;border-bottom:1px solid #f3f4f6;}\n')
f.write('tr:hover td{background:#f8f7ff;}\n')
f.write('.badge{display:inline-block;padding:3px 10px;border-radius:20px;font-size:12px;font-weight:500;}\n')
f.write('.badge-consultation{background:#e0e7ff;color:#3730a3;}\n')
f.write('.badge-fitting{background:#fce7f3;color:#9d174d;}\n')
f.write('.badge-sewing{background:#d1fae5;color:#065f46;}\n')
f.write('.badge-class{background:#fef3c7;color:#92400e;}\n')
f.write('.badge-delivery{background:#dbeafe;color:#1e40af;}\n')
f.write('.badge-other{background:#f3f4f6;color:#374151;}\n')
f.write('.badge-upcoming{background:#e0e7ff;color:#3730a3;}\n')
f.write('.badge-completed{background:#d1fae5;color:#065f46;}\n')
f.write('.badge-cancelled{background:#fee2e2;color:#991b1b;}\n')
f.write('.badge-beginner{background:#fef3c7;color:#92400e;}\n')
f.write('.badge-intermediate{background:#dbeafe;color:#1e40af;}\n')
f.write('.badge-advanced{background:#d1fae5;color:#065f46;}\n')
f.write('.btn{display:inline-block;padding:8px 18px;border-radius:8px;font-size:14px;font-weight:500;cursor:pointer;border:none;text-decoration:none;transition:all 0.2s;}\n')
f.write('.btn-primary{background:#3730a3;color:white;}\n')
f.write('.btn-primary:hover{background:#4f46e5;}\n')
f.write('.empty{text-align:center;padding:40px;color:#9ca3af;font-size:14px;}\n')
f.write('input[type=text],input[type=email],input[type=date],input[type=time],input[type=number],select,textarea{width:100%;padding:8px 12px;border:1px solid #e5e7eb;border-radius:8px;font-size:14px;color:#1a1a2e;background:#f9fafb;outline:none;transition:border 0.2s;font-family:"Segoe UI",sans-serif;}\n')
f.write('input:focus,select:focus,textarea:focus{border-color:#3730a3;background:white;box-shadow:0 0 0 3px rgba(55,48,163,0.1);}\n')
f.write('.search-bar{display:flex;gap:12px;margin-bottom:20px;flex-wrap:wrap;}\n')
f.write('.search-bar input{max-width:320px;}\n')
f.write('@media(max-width:768px){\n')
f.write('.sidebar{transform:translateX(-100%);}\n')
f.write('.sidebar.open{transform:translateX(0);}\n')
f.write('.overlay.open{display:block;}\n')
f.write('.main{margin-left:0;padding:16px;}\n')
f.write('.hamburger{display:block;}\n')
f.write('.stats{grid-template-columns:repeat(2,1fr);}\n')
f.write('.topbar{padding:12px 16px;}\n')
f.write('.topbar h1{font-size:16px;}\n')
f.write('.card{padding:16px;}\n')
f.write('}\n')
f.write('@media(max-width:400px){\n')
f.write('.stats{grid-template-columns:1fr 1fr;gap:10px;}\n')
f.write('.stat .num{font-size:24px;}\n')
f.write('}\n')
f.write('</style>\n')
f.write('</head>\n')
f.write('<body>\n')
f.write('<div class="overlay" id="overlay" onclick="closeSidebar()"></div>\n')
f.write('<div class="sidebar" id="sidebar">\n')
f.write('  <div class="logo">Vic_nice<span>Home Concepts</span></div>\n')
f.write('  <a href="/" onclick="closeSidebar()">Dashboard</a>\n')
f.write('  <a href="/appointments/" onclick="closeSidebar()">Appointments</a>\n')
f.write('  <a href="/clients/" onclick="closeSidebar()">Clients</a>\n')
f.write('  <a href="/students/" onclick="closeSidebar()">Students</a>\n')
f.write('  <a href="/calendar/" onclick="closeSidebar()">Calendar</a>\n')
f.write('  <a href="/admin/" onclick="closeSidebar()">Admin</a>\n')
f.write('</div>\n')
f.write('<div class="main">\n')
f.write('  <div class="topbar">\n')
f.write('    <button class="hamburger" onclick="openSidebar()">\n')
f.write('      <span></span><span></span><span></span>\n')
f.write('    </button>\n')
f.write('    <h1>{% block title %}Vic_nice Home Concepts{% endblock %}</h1>\n')
f.write('    <span class="date">{% now "N j, Y" %}</span>\n')
f.write('  </div>\n')
f.write('  {% block content %}{% endblock %}\n')
f.write('</div>\n')
f.write('<script>\n')
f.write('function openSidebar(){document.getElementById("sidebar").classList.add("open");document.getElementById("overlay").classList.add("open");}\n')
f.write('function closeSidebar(){document.getElementById("sidebar").classList.remove("open");document.getElementById("overlay").classList.remove("open");}\n')
f.write('</script>\n')
f.write('</body>\n')
f.write('</html>\n')
f.close()
print('Mobile-friendly base.html done!')