f = open('scheduler/templates/scheduler/base.html', 'w', encoding='utf-8')
f.write('<!DOCTYPE html>\n')
f.write('<html lang="en">\n')
f.write('<head>\n')
f.write('<meta charset="UTF-8">\n')
f.write('<meta name="viewport" content="width=device-width, initial-scale=1.0">\n')
f.write('<title>Vic_nice Home Concepts</title>\n')
f.write('<style>\n')
f.write('@import url("https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap");\n')
f.write('*{margin:0;padding:0;box-sizing:border-box;}\n')
f.write('body{font-family:"Inter",sans-serif;background:linear-gradient(135deg,#f5f3ff 0%,#ede9fe 50%,#faf5ff 100%);min-height:100vh;color:#1a1a2e;}\n')
f.write('.sidebar{position:fixed;top:0;left:0;width:240px;height:100vh;background:linear-gradient(180deg,#7c3aed 0%,#9333ea 50%,#a855f7 100%);color:white;padding:0;overflow-y:auto;z-index:1000;transition:transform 0.3s ease;box-shadow:4px 0 20px rgba(124,58,237,0.3);}\n')
f.write('.sidebar .logo{padding:28px 24px;border-bottom:1px solid rgba(255,255,255,0.15);background:rgba(0,0,0,0.1);}\n')
f.write('.sidebar .logo h2{font-size:20px;font-weight:700;color:white;letter-spacing:-0.5px;}\n')
f.write('.sidebar .logo span{display:block;font-size:12px;font-weight:400;opacity:0.7;margin-top:3px;letter-spacing:0.5px;text-transform:uppercase;}\n')
f.write('.nav-section{padding:16px 0;}\n')
f.write('.nav-label{padding:8px 24px;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:1px;opacity:0.5;}\n')
f.write('.sidebar a{display:flex;align-items:center;gap:12px;padding:12px 24px;color:rgba(255,255,255,0.8);text-decoration:none;font-size:14px;font-weight:500;transition:all 0.2s ease;border-left:3px solid transparent;}\n')
f.write('.sidebar a:hover{background:rgba(255,255,255,0.15);color:white;border-left-color:white;padding-left:28px;}\n')
f.write('.sidebar a.active{background:rgba(255,255,255,0.2);color:white;border-left-color:white;}\n')
f.write('.sidebar .logout-link{position:absolute;bottom:0;width:100%;border-top:1px solid rgba(255,255,255,0.15);background:rgba(0,0,0,0.1);}\n')
f.write('.main{margin-left:240px;padding:32px;min-height:100vh;}\n')
f.write('.topbar{background:white;border-radius:16px;padding:18px 28px;margin-bottom:28px;display:flex;justify-content:space-between;align-items:center;box-shadow:0 4px 20px rgba(124,58,237,0.08);border:1px solid rgba(124,58,237,0.1);}\n')
f.write('.topbar h1{font-size:22px;color:#7c3aed;font-weight:700;letter-spacing:-0.5px;}\n')
f.write('.topbar .date{font-size:13px;color:#8b5cf6;background:#f5f3ff;padding:6px 14px;border-radius:20px;font-weight:500;}\n')
f.write('.hamburger{display:none;background:none;border:none;cursor:pointer;padding:4px;}\n')
f.write('.hamburger span{display:block;width:24px;height:2px;background:#7c3aed;margin:6px 0;border-radius:3px;transition:0.3s;}\n')
f.write('.overlay{display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.4);z-index:999;backdrop-filter:blur(4px);}\n')
f.write('.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:20px;margin-bottom:28px;}\n')
f.write('.stat{background:white;border-radius:16px;padding:24px;box-shadow:0 4px 20px rgba(124,58,237,0.08);border:1px solid rgba(124,58,237,0.08);transition:transform 0.2s,box-shadow 0.2s;position:relative;overflow:hidden;}\n')
f.write('.stat::before{content:"";position:absolute;top:0;left:0;right:0;height:4px;background:linear-gradient(90deg,#7c3aed,#a855f7);}\n')
f.write('.stat:hover{transform:translateY(-2px);box-shadow:0 8px 30px rgba(124,58,237,0.15);}\n')
f.write('.stat .num{font-size:36px;font-weight:700;color:#7c3aed;letter-spacing:-1px;}\n')
f.write('.stat .label{font-size:13px;color:#8b5cf6;margin-top:6px;font-weight:500;}\n')
f.write('.card{background:white;border-radius:16px;padding:28px;box-shadow:0 4px 20px rgba(124,58,237,0.08);margin-bottom:24px;border:1px solid rgba(124,58,237,0.08);transition:box-shadow 0.2s;}\n')
f.write('.card:hover{box-shadow:0 8px 30px rgba(124,58,237,0.12);}\n')
f.write('.card h2{font-size:17px;font-weight:600;color:#7c3aed;margin-bottom:20px;padding-bottom:14px;border-bottom:2px solid #f5f3ff;display:flex;align-items:center;justify-content:space-between;}\n')
f.write('table{width:100%;border-collapse:collapse;}\n')
f.write('th{text-align:left;padding:12px 16px;font-size:11px;color:#8b5cf6;border-bottom:2px solid #f5f3ff;text-transform:uppercase;letter-spacing:0.08em;font-weight:600;}\n')
f.write('td{padding:14px 16px;font-size:14px;border-bottom:1px solid #faf5ff;transition:background 0.15s;}\n')
f.write('tr:hover td{background:#faf5ff;}\n')
f.write('.table-wrap{overflow-x:auto;border-radius:12px;}\n')
f.write('.badge{display:inline-flex;align-items:center;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:500;letter-spacing:0.02em;}\n')
f.write('.badge-consultation{background:#ede9fe;color:#6d28d9;}\n')
f.write('.badge-fitting{background:#fce7f3;color:#9d174d;}\n')
f.write('.badge-sewing{background:#d1fae5;color:#065f46;}\n')
f.write('.badge-class{background:#fef3c7;color:#92400e;}\n')
f.write('.badge-delivery{background:#dbeafe;color:#1e40af;}\n')
f.write('.badge-other{background:#f3f4f6;color:#374151;}\n')
f.write('.badge-upcoming{background:#ede9fe;color:#6d28d9;}\n')
f.write('.badge-completed{background:#d1fae5;color:#065f46;}\n')
f.write('.badge-cancelled{background:#fee2e2;color:#991b1b;}\n')
f.write('.badge-beginner{background:#fef3c7;color:#92400e;}\n')
f.write('.badge-intermediate{background:#dbeafe;color:#1e40af;}\n')
f.write('.badge-advanced{background:#d1fae5;color:#065f46;}\n')
f.write('.btn{display:inline-flex;align-items:center;gap:6px;padding:9px 20px;border-radius:10px;font-size:14px;font-weight:500;cursor:pointer;border:none;text-decoration:none;transition:all 0.2s ease;}\n')
f.write('.btn-primary{background:linear-gradient(135deg,#7c3aed,#9333ea);color:white;box-shadow:0 4px 12px rgba(124,58,237,0.3);}\n')
f.write('.btn-primary:hover{transform:translateY(-1px);box-shadow:0 6px 16px rgba(124,58,237,0.4);}\n')
f.write('.btn-sm{padding:5px 12px;font-size:12px;border-radius:8px;}\n')
f.write('.btn-danger{background:#fee2e2;color:#991b1b;}\n')
f.write('.btn-danger:hover{background:#fecaca;}\n')
f.write('.btn-success{background:#d1fae5;color:#065f46;}\n')
f.write('.btn-success:hover{background:#a7f3d0;}\n')
f.write('.empty{text-align:center;padding:50px;color:#a78bfa;font-size:14px;}\n')
f.write('.empty::before{content:"📅";display:block;font-size:32px;margin-bottom:12px;}\n')
f.write('input[type=text],input[type=email],input[type=date],input[type=time],input[type=number],select,textarea{width:100%;padding:10px 14px;border:2px solid #ede9fe;border-radius:10px;font-size:14px;color:#1a1a2e;background:#faf5ff;outline:none;transition:all 0.2s;font-family:"Inter",sans-serif;}\n')
f.write('input:focus,select:focus,textarea:focus{border-color:#7c3aed;background:white;box-shadow:0 0 0 4px rgba(124,58,237,0.1);}\n')
f.write('.search-bar{display:flex;gap:12px;margin-bottom:24px;flex-wrap:wrap;}\n')
f.write('.search-bar input{max-width:340px;}\n')
f.write('.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;}\n')
f.write('.form-field{display:flex;flex-direction:column;gap:6px;}\n')
f.write('.form-field label{font-size:13px;color:#6d28d9;font-weight:600;}\n')
f.write('.alert-success{padding:14px 18px;background:linear-gradient(135deg,#d1fae5,#a7f3d0);color:#065f46;border-radius:10px;margin-bottom:20px;font-size:14px;font-weight:500;border-left:4px solid #10b981;}\n')
f.write('.alert-error{padding:14px 18px;background:linear-gradient(135deg,#fee2e2,#fecaca);color:#991b1b;border-radius:10px;margin-bottom:20px;font-size:14px;font-weight:500;border-left:4px solid #ef4444;}\n')
f.write('@keyframes fadeIn{from{opacity:0;transform:translateY(10px);}to{opacity:1;transform:translateY(0);}}\n')
f.write('.card,.stat{animation:fadeIn 0.3s ease forwards;}\n')
f.write('@media(max-width:768px){\n')
f.write('.sidebar{transform:translateX(-100%);}\n')
f.write('.sidebar.open{transform:translateX(0);}\n')
f.write('.overlay.open{display:block;}\n')
f.write('.main{margin-left:0;padding:16px;}\n')
f.write('.hamburger{display:block;}\n')
f.write('.stats{grid-template-columns:repeat(2,1fr);gap:14px;}\n')
f.write('.topbar{padding:14px 16px;}\n')
f.write('.topbar h1{font-size:17px;}\n')
f.write('.form-grid{grid-template-columns:1fr;}\n')
f.write('.card{padding:20px;}\n')
f.write('}\n')
f.write('</style>\n')
f.write('</head>\n')
f.write('<body>\n')
f.write('<div class="overlay" id="overlay" onclick="closeSidebar()"></div>\n')
f.write('<div class="sidebar" id="sidebar">\n')
f.write('  <div class="logo">\n')
f.write('    <h2>Vic_nice</h2>\n')
f.write('    <span>Home Concepts</span>\n')
f.write('  </div>\n')
f.write('  <div class="nav-section">\n')
f.write('    <div class="nav-label">Main Menu</div>\n')
f.write('    <a href="/" onclick="closeSidebar()">&#9632; Dashboard</a>\n')
f.write('    <a href="/appointments/" onclick="closeSidebar()">&#9632; Appointments</a>\n')
f.write('    <a href="/clients/" onclick="closeSidebar()">&#9632; Clients</a>\n')
f.write('    <a href="/students/" onclick="closeSidebar()">&#9632; Students</a>\n')
f.write('    <a href="/calendar/" onclick="closeSidebar()">&#9632; Calendar</a>\n')
f.write('  </div>\n')
f.write('  <div class="nav-section">\n')
f.write('    <div class="nav-label">System</div>\n')
f.write('    <a href="/admin/" onclick="closeSidebar()">&#9632; Admin Panel</a>\n')
f.write('  </div>\n')
f.write('  <div class="logout-link">\n')
f.write('    <a href="/logout/" onclick="closeSidebar()" style="color:#fca5a5;">&#9632; Logout</a>\n')
f.write('  </div>\n')
f.write('</div>\n')
f.write('<div class="main">\n')
f.write('  <div class="topbar">\n')
f.write('    <div style="display:flex;align-items:center;gap:16px;">\n')
f.write('      <button class="hamburger" onclick="openSidebar()"><span></span><span></span><span></span></button>\n')
f.write('      <h1>{% block title %}Vic_nice Home Concepts{% endblock %}</h1>\n')
f.write('    </div>\n')
f.write('    <span class="date">{% now "N j, Y" %}</span>\n')
f.write('  </div>\n')
f.write('  {% block content %}{% endblock %}\n')
f.write('</div>\n')
f.write('<script>\n')
f.write('function openSidebar(){document.getElementById("sidebar").classList.add("open");document.getElementById("overlay").classList.add("open");}\n')
f.write('function closeSidebar(){document.getElementById("sidebar").classList.remove("open");document.getElementById("overlay").classList.remove("open");}\n')
f.write('</script>\n')
f.write('</body>\n')
f.write('</html>\n')
f.close()
print('Beautiful base.html done!')